### ISSUE TITLE
Add support for pushing the database

### ISSUE THREAD

**Issue by chasegiunta** [simple-integrated-marketing/swiff#13]
This would definitely have to be in conjunction with #4, but it would be useful during initial developments of a site to push a local database to a remote environment (99% of the time, a staging server).

Currently, since multi-environments aren't supported, our staging site is configured in swiff, and we're manually uploading the local database to the staging server to let the client see incremental work.

**Comment by ben-rogerson** [comment]
A task that replaces the remote database with your local database is a great feature! 
Perhaps it could be triggered with a command like:
`swiff --updb` or `swiff --uploaddb`
And those who use the staging as the master database could use the feature to populate the remote for the first time.
Thanks for your request and I'll let you know when it's available  👍

**Comment by chrisrowe** [comment]
That'd be swell

**Comment by jalendport** [comment]
This seems to be something Good Work really wants judging from who's commented and upvoted so far 😂

**Comment by ben-rogerson** [comment]
Don't worry, I'm working on the feature as we speak :)

Here's an idea of the steps Swiff will perform:
1. SSH into remote
2. Dump and gzip remote db
3. Download remote db and store in backups
4. Dump local db and gzip
5. Upload db to remote
6. Import db into remote
7. Clean up

Hope to have it released soon, I'll let you know.

**Comment by ben-rogerson** [comment]
Apologies for the delay on this, there's some issues that surfaced after adding this feature so I'm working through those at the moment. Aiming for next release within a week, should be sweet.

**Comment by chasegiunta** [comment]
@ben-rogerson No need to apologize. Appreciate your work! Excited!

**Comment by chrisrowe** [comment]
Awesome, thanks @ben-rogerson 💓

**Comment by ben-rogerson** [comment]
@chasegiunta @chrisrowe Hope you guys had a great easter holiday! 

**Swiff v1.4.0 was just released 🥳**
If you want to give it a whirl: `npm install --global swiff`
[Release notes](https://github.com/simple-integrated-marketing/swiff/releases/tag/v1.4.0)
Closing this issue for now as the database push task is now available 👍
