### ISSUE TITLE
Swiff doesn't exit after performing a database pull

### ISSUE THREAD

**Issue by jalendport** [simple-integrated-marketing/swiff#31]
After pulling a remote DB, I have to `Ctrl + C` to get my prompt back. I'm guessing (without checking into the source) that perhaps you're not sending the proper exit codes to the terminal after performing the DB pull, so it never knows that the task is done.

**Comment by ben-rogerson** [comment]
Hey Jalen! That sounds like the default functionality of Swiff. The app stays open until you close it (esc also works). We commonly keep it open in a CLI tab that way we don't need to relaunch it. 

There's flag shortcut commands (check `swiff --help`) that act more like you're expecting but I was a sausage head and broke them in the last update. I'll be fixing that back up shortly.

**Comment by jalendport** [comment]
Ah I didn't realize that was an intended feature - didn't realize either you could still navigate the main menu after the task runs. Thanks for clearing things up!
