### ISSUE TITLE
Add a pre-push to production confirmation

### ISSUE THREAD

**Issue by ben-rogerson** [simple-integrated-marketing/swiff#4]
Pushing to production isn't the safest / best thing to do so I'm thinking of adding 'are you sure' prompt before it sync up the files.
That'll make it harder to accidentally ruin your week :)

**Comment by ben-rogerson** [comment]
Added the ability to disable tasks in v1.5.0. This should help avoid this problem.

**Comment by samstevens** [comment]
Thank you Ben. 

I can now sleep at night 😁
