### ISSUE TITLE
I'm getting: "TypeError: ssh.dispose is not a function"

### ISSUE THREAD

**Issue by mblode** [simple-integrated-marketing/swiff#7]
After installing Swiff and setting up the config, I received an error when running Pull, Push and Database. It says "Performing pre-task checks" and then fails with this message:

``` sh

TypeError: ssh.dispose is not a function
    at /Users/matthewblode/.nvm/versions/node/v11.7.0/lib/node_modules/swiff/dist/ssh.js:136:11
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/matthewblode/.nvm/versions/node/v11.7.0/lib/node_modules/swiff/dist/ssh.js:32:103)
    at _next (/Users/matthewblode/.nvm/versions/node/v11.7.0/lib/node_modules/swiff/dist/ssh.js:34:194)

```

I'm running Node 11.7.0, the latest version. Thank you! Great concept and super easy to set-up if it works... 😬

**Comment by ben-rogerson** [comment]
@mblode Hey looks like your machine can't connect to the remote with your config details / your ssh key isn't on the remote machine. I'll fix that error so you can see what's going wrong.

**Comment by ben-rogerson** [comment]
Hey @mblode I've now improved the feedback errors in that area of the app.
Update to 1.1.4 by running `npm i -g swiff`
Let me know if there's any other issues 🤞

**Comment by mblode** [comment]
Works perfectly thank you! Should the terminal be exiting (equivalent of control+c) after completing the pull from the server?

**Comment by ben-rogerson** [comment]
Good to hear :)
I shouldn't exit if you're running pull via the interface (after running `swiff`).
But if you're running `swiff --pull` it will exit afterwards.

**Comment by mblode** [comment]
Ok, that makes perfect sense. Thank you!
